env:
  - DB=sqlite
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
  - bundle exec sunspot-solr start -p 8983
  - ps
  - bundle exec rake sunspot:solr:reindex
  - bundle exec cucumber
  - bundle exec rake spec
  - bundle exec sunspot-solr stop

language: ruby
rvm:
  - 2.2.2

before_script:
  - cat `find . -name 'scripts.conf' -print`
  - ps
