
env:
  - DB=sqlite
before_script:
  - bundle exec sunspot-solr start -p 8983
script:
  - bundle exec rake db:reset
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
  - bundle exec rake sunspot:solr:reindex
  - bundle exec cucumber
  - bundle exec rake spec
after_script:
  - bundle exec sunspot-solr stop

language: ruby
rvm:
  - 2.3.0

addons:
    code_climate:
        repo_token: ac97436e749c29abf4fc563d5137342cf6ae061900729618331f5dab4e4275f6
