env:
  - DB=sqlite
script: 
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec sunspot-solr start -p 8981
  - bundle exec rake sunspot:solr:reindex
  - cucumber
  - bundle exec rake spec
  - bundle exec sunspot-solr stop

language: ruby
rvm:
  - 1.9.3