#!/usr/bin/env rake
# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Coursequestionbank::Application.load_tasks

task :default => [:test]

desc "Clean cached file generated by server run. Do it before commit."
task :clean do
  sh "git clean  -d  -fx "
end